[package]
name = "house-snark"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
blake2 = "0.9.2"
clap = { version = "4.0", features = ["derive"] }
color-eyre = "0.6"
env_logger = "0.9.0"
log = "0.4"
relations = { path = "/home/filip/CloudStation/aleph/aleph-node/relations" }
