name: Checks

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup component add clippy rustfmt


      - name: Run format check for `house-snark`
        run: cd house-snark/ && cargo fmt --all --check

      - name: Run clippy for `house-snark`
        run: cd house-snark/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `house-snark`
        run: cd house-snark/ && cargo test


      - name: Run format check for `snarkxt`
        run: cd snarkxt/ && cargo fmt --all --check

      - name: Run clippy for `snarkxt`
        run: cd snarkxt/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `snarkxt`
        run: cd snarkxt/ && cargo test


      - name: Run format check for `shielder-cli`
        run: cd shielder-cli/ && cargo fmt --all --check

      - name: Run clippy for `shielder-cli`
        run: cd shielder-cli/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder-cli`
        run: cd shielder-cli/ && cargo test
